# Generated by Django 6.1.1 on 2026-10-06 02:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=50, unique=True)),
                ('robot_type', models.CharField(choices=[('picker', 'Picker'), ('hauler', 'Hauler')], max_length=20)),
                ('x', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(900)])),
                ('y', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(560)])),
                ('battery', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('on_mission', 'On Mission'), ('charging', 'Charging'), ('blocked', 'Blocked'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='idle', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['robot_id'],
            },
        ),
        migrations.CreateModel(
            name='RobotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('battery', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('on_mission', 'On Mission'), ('charging', 'Charging'), ('blocked', 'Blocked'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], max_length=20)),
                ('task_event', models.CharField(blank=True, max_length=30, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='robots.robot')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['robot', 'timestamp'], name='robots_robo_robot_i_619b2d_idx'), models.Index(fields=['status', 'timestamp'], name='robots_robo_status_f6c58f_idx')],
            },
        ),
    ]
